// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuw8-9eVi3o3dnWGVk0tHR3F8vrgBTClA',
    appId: '1:764145042226:web:6fc9e4dbe8f977d1394d2b',
    messagingSenderId: '764145042226',
    projectId: 'pushnotification-1a017',
    authDomain: 'pushnotification-1a017.firebaseapp.com',
    databaseURL: 'https://pushnotification-1a017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pushnotification-1a017.firebasestorage.app',
    measurementId: 'G-HVQVBLC9TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlStTlub6KdbdzTnr3_rvjmH-2VQG2uSk',
    appId: '1:764145042226:android:6375fff66e6a8a4c394d2b',
    messagingSenderId: '764145042226',
    projectId: 'pushnotification-1a017',
    databaseURL: 'https://pushnotification-1a017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pushnotification-1a017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcqKo_zW_0AJq8Klz_rlka39Zy7tbmkY',
    appId: '1:764145042226:ios:e225fd5f5383704f394d2b',
    messagingSenderId: '764145042226',
    projectId: 'pushnotification-1a017',
    databaseURL: 'https://pushnotification-1a017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pushnotification-1a017.firebasestorage.app',
    iosBundleId: 'com.example.hoardlinks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcqKo_zW_0AJq8Klz_rlka39Zy7tbmkY',
    appId: '1:764145042226:ios:e225fd5f5383704f394d2b',
    messagingSenderId: '764145042226',
    projectId: 'pushnotification-1a017',
    databaseURL: 'https://pushnotification-1a017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pushnotification-1a017.firebasestorage.app',
    iosBundleId: 'com.example.hoardlinks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuw8-9eVi3o3dnWGVk0tHR3F8vrgBTClA',
    appId: '1:764145042226:web:adde51d3185d5f7e394d2b',
    messagingSenderId: '764145042226',
    projectId: 'pushnotification-1a017',
    authDomain: 'pushnotification-1a017.firebaseapp.com',
    databaseURL: 'https://pushnotification-1a017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pushnotification-1a017.firebasestorage.app',
    measurementId: 'G-CFRZWL4552',
  );
}
